### ISSUE TITLE
Preferir etiquetas semánticas

### ISSUE THREAD

**Issue by DanBaDo** [KhrisDV/Curriculum#1]
https://github.com/KhrisDV/Curriculum/blob/7609a7a9c311e28743832014a91c84e39d7aae8c/src/index.html#L23

En este caso podrías emplear una etiqueta `<main>` para agrupar los elementos y aplicar formatos, reforzando el significado del bloque de cara a los navegadores.

**Comment by KhrisDV** [comment]
Arreglado siguiendo indicaciones.
